services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - database.env
    restart: on-failure
  web:
    depends_on:
      - db
    build: ./
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    env_file:
      - database.env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    restart: on-failure
volumes:
  database-data: