# Generated by Django 4.1.5 on 2023-01-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_field_name_alter_homestead_name_alter_location_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.location')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField()),
                ('percent', models.IntegerField()),
                ('classification_detail', models.TextField()),
                ('paid_external', models.BooleanField()),
                ('paid_internal', models.BooleanField()),
                ('approved', models.BooleanField(default=True)),
                ('store', models.CharField(max_length=255)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.expenseclassification')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debtor', to='home.staff')),
                ('spender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='spender', to='home.staff')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.supplier')),
            ],
        ),
    ]
