# Generated by Django 4.1.5 on 2023-01-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_project_capitalinvestment_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
