# Generated by Django 4.1.5 on 2023-02-04 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_location_homestead'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.roleclasses'),
            preserve_default=False,
        ),
    ]
