# Generated by Django 5.0.3 on 2024-03-27 00:35

import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_remove_field_name_alter_budget_property_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capitalinvestment",
            name="investment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="capitalinvestment",
            name="investment_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 27, 0, 35, 34, 100389, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
