# Generated by Django 5.0.3 on 2024-03-27 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_capitalinvestment_investment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capitalinvestment",
            name="investment_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
