# Generated by Django 5.0.3 on 2024-04-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_crop_plant_target_date_alter_crop_yield_actual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="staff_responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="home.staff",
            ),
        ),
    ]
